# dropbox_backup_to_external_disk/Makefile.toml
# https://github.com/sagiegurari/cargo-make/blob/master/src/lib/Makefile.stable.toml

[config]
skip_core_tasks = true

[tasks.default]
description = "help for prepared make tasks"
clear = true
script= [
"clear",
"echo ",
"echo HELP FOR MAKE TASKS:",
"echo ",
"echo $ clear - clear the screen",
"echo $ cargo make - this list",
"echo $ cargo make debug - build debug version, increment semver patch in Cargo.toml",
"echo $ cargo make doc - includes from Cargo.toml to README.md and from README.md to main.rs or lib.rs, generates doc and copies to docs folder, exports codetour to .md.",
"echo ",
"echo create alias for easy use",
"echo $ alias dropbox_backup_to_external_disk=target/debug/dropbox_backup_to_external_disk",
"echo $ dropbox_backup_to_external_disk --help - instructions especially for first use because of authentication",
"echo "
]

# end of help
# end of help
# end of help

[tasks.debug]
description = "cargo build debug"
clear = true
script = [    
    # Binaries version is date
    #"echo $ lmake_version_from_date",
    #"lmake_version_from_date",
    # Library version is semver
    "echo $ lmake_semver --increment=patch",
    "lmake_semver --increment=patch",
    "echo $ cargo build",
    "cargo build",
    "echo $ alias dropbox_backup_to_external_disk=target/debug/dropbox_backup_to_external_disk",
    "alias dropbox_backup_to_external_disk=target/debug/dropbox_backup_to_external_disk",
    "echo $ dropbox_backup_to_external_disk --help",
    "dropbox_backup_to_external_disk --help"
]

# end of run scripts
# end of run scripts
# end of run scripts

[tasks.doc]
description = "cargo doc - create docs from doc comments"
clear = true
script= [
    "echo $ lmake_lines_of_code",
    "lmake_lines_of_code",
    "echo $ lmake_cargo_toml_to_md",
    "lmake_cargo_toml_to_md",
    "echo $ lmake_md_to_doc_comments",
    "lmake_md_to_doc_comments",
    "echo $ cargo doc --no-deps --document-private-items",
    # create doc from doc comments
    "cargo doc --no-deps --document-private-items",
    "echo $ codetour_export_to_md",
    # export code tour to md
    "codetour_export_to_md",
    # copy to /docs/ because it is github standard
    "echo $ rsync -a --info=progress2 --delete-after target/doc/ docs/",
    "rsync -a --info=progress2 --delete-after target/doc/ docs/",
    "echo Create simple index.html file in docs folder",
    "echo \"<meta http-equiv=\\\"refresh\\\" content=\\\"0; url=${CARGO_MAKE_CRATE_NAME}/index.html\\\" />\" > docs/index.html",
    # message to help user with next move
    "echo After successful doc, commit and push changes",
]

# end of publish script
# end of publish script
# end of publish script

# end of crates.io publish script
# end of crates.io publish script
# end of crates.io publish script
